### PR TITLE
Adjust API Availability for Structured Concurrency Backport

### PR DESCRIPTION
**Pull request by moritzsternemann**
As the Swift Structured Concurrency backport is now available with the [release of Xcode 13.2](https://developer.apple.com/documentation/xcode-release-notes/xcode-13_2-release-notes), I adjusted the API availability guards to enable these features on previous OS versions.

I'll also open a follow-up PR in [swift-distributed-tracing](https://github.com/apple/swift-distributed-tracing).

### CODE REVIEW

**Review by slashmo — COMMENTED** [review]
Thanks for your PR, @moritzsternemann! Looks good to me ✅ I'm wondering if we should also add `#if compiler(>=5.5.2) && canImport(_Concurrency)`, because that's how it's [currently handled in NIO](https://github.com/apple/swift-nio/blob/main/Sources/NIOCore/AsyncAwaitSupport.swift#L21). CC @ktoso, @fabianfett

**Comment by ktoso** [comment]
@swift-server-bot test this please

**Comment by ktoso** [comment]
Yeah the `#if` also has to be adjusted to what we explain in the adoption guidelines: https://github.com/swift-server/guides/blob/main/docs/concurrency-adoption-guidelines.md#if-guarding-code-using-concurrency

**Comment by ktoso** [comment]
Our "good friend" jazzy messing up builds again, I'll fix this.

**Comment by slashmo** [comment]
> Our "good friend" jazzy messing up builds again, I'll fix this.
> @ktoso 

Now that DocC seems to be able to generate static websites as well (https://github.com/apple/swift-docc/pull/56), I think we can ditch Jazzy as soon as possible.

**Comment by ktoso** [comment]
Very true, to be honest perhaps let's not even waste energy on jazzy anymore.

**Comment by ktoso** [comment]
@swift-server-bot test this please

**Comment by ktoso** [comment]
I updated the check: https://github.com/apple/swift-distributed-tracing-baggage/pull/18/commits/46faa2a1be2c95c22f5c181276996d7d9ce75e33

Would you mind doing the same in the other repo @moritzsternemann ?

**Comment by ktoso** [comment]
@swift-server-bot add to whitelist

**Comment by ktoso** [comment]
@swift-server-bot add to allowlist

**Review by ktoso — APPROVED** [review]

**Pull request merged**
