### PR TITLE
Delete docker-compose.1804.54.yaml

### PR DESCRIPTION
**Pull request by ktoso**
CI should use the 20.04 files now, could you change that @tomerd ?

### CODE REVIEW

**Comment by yim-lee** [comment]
Updated 5.4 and 5.5 jobs to  use `x.2004.x`

@swift-server-bot test this please

**Review by yim-lee — APPROVED** [review]

**Comment by yim-lee** [comment]
@swift-server-bot test this please

**Comment by yim-lee** [comment]
@swift-server-bot test this please

**Comment by ktoso** [comment]
Thank you!

**Pull request merged**
